version: '3.5'

services:

  configsrv1:
    build: .
    image: stutzlab/mongo-cluster-configsrv
    environment:
      - CONFIG_REPLICA_SET=configsrv-one
      - INIT_CONFIG_NODES=configsrv1,configsrv2,configsrv3

  configsrv2:
    build: .
    image: stutzlab/mongo-cluster-configsrv
    environment:
      - CONFIG_REPLICA_SET=configsrv-one

  configsrv3:
    build: .
    image: stutzlab/mongo-cluster-configsrv
    environment:
      - CONFIG_REPLICA_SET=configsrv-one

  configsrv4:
    build: .
    image: stutzlab/mongo-cluster-configsrv
    environment:
      - CONFIG_REPLICA_SET=configsrv-one
